### ISSUE TITLE
Where are the source images come from?

### ISSUE THREAD

**Issue by yeliudev** [OpenGVLab/MMT-Bench#3]
Thanks for sharing this work! I noticed that you mentioned in the paper all the images & raw annotations were collected from existing datasets, but without mentioning what datasets (also under what licenses) you have used. I was wondering whether you could share the source datasets used in MMT-Bench. Thanks!

**Comment by KainingYing** [comment]
Hello, @yeliudev . Thanks for your attention.

We will update the source of the datasets used in MMT-Bench in the camera-ready version of ICML2024 ASAP.

**Comment by yeliudev** [comment]
That's great! Thanks for your reply.
