### ISSUE TITLE
Where to find the answer of "test" split

### ISSUE THREAD

**Issue by AL-377** [OpenGVLab/MMT-Bench#9]
Thanks for your contribution, nice work.

I have downloaded the "TEST" split in from [MMT-Bench_ALL.tsv](https://huggingface.co/datasets/Kaining/MMT-Bench/blob/main/MMT-Bench_ALL.tsv) but there is no "answer" column, i wonder how can i get the answer of each row?

Thanks a lot.

**Comment by Morgott-The-Omen-King** [comment]
Thanks for your attention. Please follow the instructions in the following [link](https://eval.ai/web/challenges/challenge-page/2328/leaderboard/5777).

**Comment by AL-377** [comment]
> Thanks for your attention. Please follow the instructions in the following [link](https://eval.ai/web/challenges/challenge-page/2328/leaderboard/5777).

Thanks for the response. So it seems that the answers are carried only on EvalAI. Are there any possible ways to get the raw answers?

**Comment by Morgott-The-Omen-King** [comment]
Raw answer of `TEST` split  is not relaeased.
If you want to use the raw answer, you can use the `VAL` split.

**Comment by AL-377** [comment]
> Raw answer of `TEST` split is not relaeased. If you want to use the raw answer, you can use the `VAL` split.

OK，thanks for your response again.
